name: 'Flawfinder'
description: 'Execute Flawfinder'
inputs:
  arguments:
    description: 'Command arguments to be sent to Flawfinder'
    required: false
    default: ''
  output:
    description: 'Output file name'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.arguments }}
    - ${{ inputs.sourcepath }}
    - ${{ inputs.sarif }}
